#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue May 13 16:38:21 CST 2025
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 99950cfc254e48ed950a5362ccaf5f68 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot BufINOUT_tb_behav xil_defaultlib.BufINOUT_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto 99950cfc254e48ed950a5362ccaf5f68 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot BufINOUT_tb_behav xil_defaultlib.BufINOUT_tb xil_defaultlib.glbl -log elaborate.log

