webtalk_init -webtalk_dir /home/alfaquillo/Documentos/Vivado/Interfaz_de_memoria/Interfaz_de_memoria.sim/sim_1/behav/xsim/xsim.dir/GenDir_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun May 18 18:00:58 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3c22f5f9-b0a6-45ed-9f51-c092ab583915" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "99950cfc254e48ed950a5362ccaf5f68" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Fedora" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Fedora Linux 42 (KDE Plasma Desktop Edition)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3699.740 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "80 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "114672_KB" -context "xsim\\usage"
webtalk_transmit -clientid 941192334 -regid "" -xml /home/alfaquillo/Documentos/Vivado/Interfaz_de_memoria/Interfaz_de_memoria.sim/sim_1/behav/xsim/xsim.dir/GenDir_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/alfaquillo/Documentos/Vivado/Interfaz_de_memoria/Interfaz_de_memoria.sim/sim_1/behav/xsim/xsim.dir/GenDir_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/alfaquillo/Documentos/Vivado/Interfaz_de_memoria/Interfaz_de_memoria.sim/sim_1/behav/xsim/xsim.dir/GenDir_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
