#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.2.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Jun 16 11:58:13 CST 2025
# SW Build 6060944 on Thu Mar 06 19:10:09 MST 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim fpu_top_tb_time_synth -key {Post-Synthesis:sim_1:Timing:fpu_top_tb} -tclbatch fpu_top_tb.tcl -log simulate.log"
xsim fpu_top_tb_time_synth -key {Post-Synthesis:sim_1:Timing:fpu_top_tb} -tclbatch fpu_top_tb.tcl -log simulate.log

